export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const categoryConstants = {
  GETALLCATEGORY_REQUEST: "GETALLCATEGORY_REQUEST",
  GETALLCATEGORY_SUCCESS: "GETALLCATEGORY_SUCCESS",
  GETALLCATEGORY_FAILURE: "GETALLCATEGORY_FAILURE",
  ADDNEWCATEGORY_REQUEST: "ADDNEWCATEGORY_REQUEST",
  ADDNEWCATEGORY_SUCCESS: "ADDNEWCATEGORY_SUCCESS",
  ADDNEWCATEGORY_FAILURE: "ADDNEWCATEGORY_FAILURE",
  UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
  DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};
export const productConstants = {
  GET_ALL_PRODUCTS_DATA_REQUEST: "GET_ALL_PRODUCTS_DATA_REQUEST",
  GET_ALL_PRODUCTS_DATA_SUCCESS: "GET_ALL_PRODUCTS_DATA_SUCCESS",
  GET_ALL_PRODUCTS_DATA_FAILURE: "GET_ALL_PRODUCTS_DATA_FAILURE",
};
export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const createPageConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
  CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
};
