
export const categoryConstants = {
	GETALLCATEGORY_REQUEST : 'GETALLCATEGORY_REQUEST',
	GETALLCATEGORY_SUCCESS : 'GETALLCATEGORY_SUCCESS',
	GETALLCATEGORY_FAILURE : 'GETALLCATEGORY_FAILURE',
	ADDNEWCATEGORY_REQUEST : 'ADDNEWCATEGORY_REQUEST',
	ADDNEWCATEGORY_SUCCESS : 'ADDNEWCATEGORY_SUCCESS',
	ADDNEWCATEGORY_FAILURE : 'ADDNEWCATEGORY_FAILURE'
}
export const productConstants = {
	GET_PRODUCT_BT_SLUG : 'GET_PRODUCT_BT_SLUG',
	GET_PRODUCT_PAGE_REQUEST : 'GET_PRODUCT_PAGE_REQUEST',
	GET_PRODUCT_PAGE_SUCCESS : 'GET_PRODUCT_PAGE_SUCCESS',
	GET_PRODUCT_PAGE_FAILURE : 'GET_PRODUCT_PAGE_FAILURE',

	GET_PRODUCT_DETAILS_BY_ID_REQUEST : 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
	GET_PRODUCT_DETAILS_BY_ID_SUCCESS : 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
	GET_PRODUCT_DETAILS_BY_ID_FAILURE : 'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
} 
export const authConstants = {
	LOGIN_REQUEST : 'LOGIN_REQUEST',
	LOGIN_FAILURE : 'LOGIN_FAILURE',
	LOGIN_SUCCESS : 'LOGIN_SUCCESS',
	LOGOUT_REQUEST : 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE : 'LOGOUT_FAILURE'

}

export const userConstants = {
	USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
	USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
	USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE',
	GET_USER_ADDRESS_REQUEST : 'GET_USER_ADDRESS_REQUEST',
	GET_USER_ADDRESS_SUCCESS : 'GET_USER_ADDRESS_SUCCESS',
	GET_USER_ADDRESS_FAILURE : 'GET_USER_ADDRESS_FAILURE',
	ADD_USER_ADDRESS_REQUEST : 'ADD_USER_ADDRESS_REQUEST',
	ADD_USER_ADDRESS_SUCCESS : 'ADD_USER_ADDRESS_SUCCESS',
	ADD_USER_ADDRESS_FAILURE : 'ADD_USER_ADDRESS_FAILURE'
}

export const cartConstants = {
	ADD_TO_CART_REQUEST : 'ADD_TO_CART_REQUEST',
	ADD_TO_CART_SUCCESS : 'ADD_TO_CART_SUCCESS',
	ADD_TO_CART_FAILURE : 'ADD_TO_CART_FAILURE',
	REMOVE_ADD_TO_CART_REQUEST : 'REMOVE_ADD_TO_CART_REQUEST',
	REMOVE_ADD_TO_CART_SUCCESS : 'REMOVE_ADD_TO_CART_SUCCESS',
	REMOVE_ADD_TO_CART_FAILURE : 'REMOVE_ADD_TO_CART_FAILURE',
	RESET_CART : 'RESET_CART'
}

